baseURL = "http://localhost/hpc-scorpion/"
publishDir = "hpc-scorpion"
title = "Scorpion â€” HPC cluster of biology.tohoku.ac.jp"
theme = "hugo-theme-nonblog"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
name = "Watal M. Iwasaki"

[markup.goldmark.renderer]
unsafe = true

[params]
logo_src = "logo.png"
logo_alt = "logo.png"
theme_color = "#400E82"
